services:

  backend:
    container_name: api
    restart: unless-stopped
    tty: true
    build:
      context: ./api
      dockerfile: ./api.Dockerfile
    volumes:
      - ./api:/var/www
    networks:
      - app-network

  client:
    container_name: client
    command: sh -c "npm install && npm run dev"
    depends_on:
      - backend
    build:
      context: ./client
      dockerfile: ./client.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src
    networks:
      - app-network

  database:
    image: mysql:8.0
    container_name: database
    restart: unless-stopped
    tty: true
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: news-aggregator
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_ROOT_PASSWORD:
    volumes:
      - dbdata:/var/lib/mysql/
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8008:80"
    volumes:
      - ./api:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    container_name: elasticsearch
    depends_on:
      - client
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - cluster.routing.allocation.disk.threshold_enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - app-network

  kibana:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/kibana/kibana:8.8.0
    container_name: kibana
    volumes:
      - kbdata:/usr/share/kibana/data
    ports:
      - 5601:5601
    restart: always
    environment:
      ELASTICSEARCH_HOSTS: '["http://localhost:9200","http://elasticsearch:9200"]'
    networks:
      - app-network

volumes:
  dbdata:
  kbdata:
    driver: local
  esdata:
    driver: local

networks:
  app-network:
    driver: bridge
